### ISSUE TITLE
[task] Fix logger injection in nestjs-bus package

### ISSUE THREAD

**Issue by tuogeniy** [Atlantis-Lab/nestjs#114]

**Comment by tuogeniy** [comment]
Нужно диффнуть пакет atlantis-lab/nestjs-bus с @monstrs/nestjs-bus@0.1.4 и исправить нашу версию так чтобы она начала работать с https://github.com/Atlantis-Lab/serenity
Дифать нужно транслированные в js версии так как сурсов nestjs-bus от monstrs у нас нет.

**Comment by unmyke** [comment]
- `BusCoreModule`: добавить в методе `forRoot` импорт `LogggerModule`;
- HandlerRegistry: актуализировать методы `register`, `get`, `bindHandlers`; добавить методы `getMessageNames`, `getMessageConstructor`; заменить приватное поле `handlerResolvers` на `registry` и `unhandledMessages`.
