### ISSUE TITLE
[bug] adapt nestjs-bus to the updated @node-ts/bus-core & @node-ts/bus-rabbitmq

### ISSUE THREAD

**Issue by tuogeniy** [Atlantis-Lab/nestjs#156]
### Описание бага
После обновления пакета https://github.com/Atlantis-Lab/nestjs/commit/9f834cf21df4245865a41fc293e5a8d344442935 проект перестал проходить проверку типов
   
### Воспроизведение
yarn run typecheck

### Ожидаемое поведение
Проект проходит проверку без ошибок

### Данные окружения
- mac os 11.2

**Comment by TorinAsakura** [comment]
1. Надо не ошибку править
2. Нужно завести задачу по покрытию тестами
3. mac os 11.2 => macOS 11.2(ревизия версии доступна по клику по номеру версии)

**Comment by tuogeniy** [comment]
задача останется открытой так как код с обновленными библиотеками не проходит тесты написанные в https://github.com/Atlantis-Lab/nestjs/issues/186
