### ISSUE TITLE
[feature] coverage nestjs-map-errors-interceptor with tests

### ISSUE THREAD

**Issue by tuogeniy** [Atlantis-Lab/nestjs#158]
### С чем связан запрос на фичу?
необходимость покрыть код тестами

### Расскажите как вы это себе видите
nestjs-map-errors-interceptor
1. создать папку __tests__
2. Создать в папке файл в котором проверить работу класса MapValidationErrorsInterceptor

**Comment by NavruzJn** [comment]
Необходимо покрыть тестами interceptor MapValidationErrorsInterceptor как минимум в трех кейсах

1. interceptor switched to http
2. interceptor switched to rpc
2. interceptor switched to ws
